# Generated by Django 4.1.7 on 2023-03-14 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CuentaBancaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_banco", models.CharField(max_length=255)),
                ("numero_cuenta", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Gasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("categoria", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "cuenta_bancaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manejogastos.cuentabancaria",
                    ),
                ),
            ],
        ),
    ]
